INSERT INTO `CURRENCY_EXCHANGE`(`ID`,`CUR_FROM`,`CUR_TO`,`ENVIRONMENT`,`CONVERSION_MULTIPLE`)
VALUES (1001,'USD','INR','',65);
INSERT INTO `CURRENCY_EXCHANGE`(`ID`,`CUR_FROM`,`CUR_TO`,`ENVIRONMENT`,`CONVERSION_MULTIPLE`)
VALUES (1002,'EUR','INR','',75);
INSERT INTO `CURRENCY_EXCHANGE`(`ID`,`CUR_FROM`,`CUR_TO`,`ENVIRONMENT`,`CONVERSION_MULTIPLE`)
VALUES (1003,'AUD','INR','',45);
